### ISSUE TITLE
Packaged jar is not working

### ISSUE THREAD

**Issue by dkovalenko** [pantsbuild/example-jvm#5]
Hello, after a quick test I can't get working jar out of this example app.

```
% ./pants package ::                                       
14:04:12.59 [INFO] Wrote dist/src.jvm.org.pantsbuild.example.app/bin.jar
```
```
% java -jar dist/src.jvm.org.pantsbuild.example.app/bin.jar
Error: Main method is not static in class org.pantsbuild.example.app.ExampleApp, please define the main method as:
   public static void main(String[] args)
```
```
java -cp dist/src.jvm.org.pantsbuild.example.app/bin.jar org.pantsbuild.example.app.ExampleApp
Error: Main method is not static in class org.pantsbuild.example.app.ExampleApp, please define the main method as:
   public static void main(String[] args)
```

Am I doing something wrong? Thanks.

**Comment by benjyw** [comment]
Hi, I think you've found a bug in this example repo! The main() method should be in an `object`, not a `class`, IIRC. 

We'll fix this asap, thanks for the bug report!

**Comment by benjyw** [comment]
Note that running the main requires the scala runtime on the classpath. We'll add some documentation on how to do that.

**Comment by benjyw** [comment]
Fixed in https://github.com/pantsbuild/example-jvm/pull/6

**Comment by dkovalenko** [comment]
> Note that running the main requires the scala runtime on the classpath. We'll add some documentation on how to do that.

It's now clear, thanks. Is any way to "run" the application without packaging it to jar?

**Comment by benjyw** [comment]
I believe we haven't yet implemented `./pants run` for JVM, but it should be coming soon.

**Comment by benjyw** [comment]
I wonder if we should have a java-only main(), so that people can run it with `java -jar` and not have to worry about scala...

**Comment by stuhood** [comment]
Thanks for the report! Have opened https://github.com/pantsbuild/pants/issues/14171 about this. In the meantime, I'll likely declare the dependency explicitly.
