### ISSUE TITLE
Is there any way to specify resources for external libs?

### ISSUE THREAD

**Issue by dkovalenko** [pantsbuild/example-jvm#8]
Example from this repo:
```
java_sources(
    dependencies=[
        # Resource dependencies cannot be inferred, so we must explicitly declare that we
        # depend on them.
        "src/resources/org/pantsbuild/example/lib",
    ],
)
```
I tried to include dependency on resources for my "main" jar build of application:
```
scala_sources()

deploy_jar(
    name="app",
    main="MyApp",
    dependencies=[
        ":scala",
        "3rdparty/jvm/org/scala-lang:scala-library",
        "src/main/resources",
    ],
)
```
but looks like external 3rd party dependencies can't access files from the resources folder.
I tried to use logback.xml for logger configuration and application.conf for typesafe config. Both libs use files from the resources folder by convention(both logback.xml and application.conf are standard names). 
Looks like after packaging jar these libs can't access files from the resources folder. 

Is there any way to specify resources for external libs?

I can create a minimal reproducible app if you need. Thanks.

**Comment by stuhood** [comment]
Hey @dkovalenko! The important thing to confirm is that your resources are located at the proper depth below a "source root": see https://www.pantsbuild.org/docs/source-roots

In this case: if you have resources that you want to load as `logback.xml` or `application.conf`, then they must be located directly in a source root, with no additional nesting. So, if `src/main*` was configured as a source root pattern (note: it isn't by default: see the page above), then the files would need to be located at:
```
src/main/resources/logback.xml
src/main/resources/application.conf
```

**Comment by dkovalenko** [comment]
@stuhood you were right. 
```
ls -la src/main
total 0
drwxr-xr-x  4 dmitriy  staff  128 Oct 27 11:16 .
drwxr-xr-x  3 dmitriy  staff   96 Oct 26 18:46 ..
drwxr-xr-x  5 dmitriy  staff  160 Jan 26 17:29 resources
drwxr-xr-x  7 dmitriy  staff  224 Jan 19 20:59 scala
```
changed root_patterns in pants.toml 
```
[source]
root_patterns = ["/src/main/*"] // it was ["/src/*"]
```
and all worked.
Thank you!
